# Generated by Django 2.0 on 2019-02-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='login',
            field=models.BooleanField(default=False),
        ),
    ]
