# Generated by Django 2.0 on 2019-01-13 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=100)),
                ('vehicle_pic', models.TextField(max_length=100000)),
                ('time_recorded', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('place_name', models.TextField(blank=True, null=True)),
                ('known_location', models.BooleanField(default=False)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('bearing', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=100, null=True)),
                ('time_recorded', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100, null=True)),
                ('conductor', models.CharField(max_length=100, null=True)),
                ('assign_time', models.DateTimeField(null=True)),
                ('route', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100, unique=True)),
                ('running_status', models.BooleanField(default=False)),
                ('shifts', models.IntegerField(default=0, null=True)),
                ('installation_date', models.CharField(max_length=50, null=True)),
                ('expiry_date', models.CharField(max_length=50, null=True)),
                ('previous_latitude', models.FloatField(blank=True, null=True)),
                ('previous_longitude', models.FloatField(blank=True, null=True)),
                ('place_name', models.CharField(blank=True, max_length=200, null=True)),
                ('distance_travel', models.FloatField(blank=True, default=0, null=True)),
                ('type_of_device', models.CharField(max_length=100, null=True)),
                ('is_disconnected', models.BooleanField(default=False)),
            ],
        ),
    ]
