# Generated by Django 2.0 on 2019-01-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20190113_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='assign_time',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='shifts',
        ),
    ]
